trigger:
- v1.3-dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Install Node.js'

- script: |
      npm install
      mkdir config
      echo '{"debug":false,"token":"","apiSite":4,"apiUrl":"https://full uri here","serverIp":"","serverPort":"28015","queueMessage":"currently waiting in queue.","updateInterval":"1"}' > config/server1.json
  displayName: 'npm install'

- bash: |
      timeout 20s npm start
      exit 0
  displayName: 'Testing apisite 2 config'
  env:
    token: '$(discord_token)'
    apiSite: '$(apisite2)'
    apiUrl: '$(apiurl2)'

- bash: |
      timeout 20s npm start
      exit 0
  displayName: 'Testing apisite 3 config'
  env:
    token: '$(discord_token)'
    apiSite: '$(apisite3)'
    apiUrl: '$(apiurl3)'

- bash: |
      timeout 20s npm start
      exit 0
  displayName: 'Testing apisite 4 config'
  env:
    token: '$(discord_token)'
    apiSite: '$(apisite4)'
    serverIp: '$(server)'
    serverPort: '$(port)'
