version: '2'
services:
  bot:
    build: .
    image: kenrisa/discord-rustserverstatus
    container_name: discord-rustserverstatus
    restart: unless-stopped
    environment:
      - debug=false
      - token=
      - apiSite=4
      - apiUrl=https://api.battlemetrics.com/servers/
      - serverIp=
      - serverPort=
      - "queueMessage=currently waiting in queue"
      - updateInterval=1